### PR TITLE
use northstar-php

### LINKED ISSUE #487: Northstar connection having issues
We're getting errors when trying to forward user's interests (e.g. candidate category) to Northstar:

```
[2015-12-02 18:10:14] production.DEBUG: Northstar API Exception {
  "code":405,
  "message":"Client error response [url] https://northstar.dosomething.org/v1/users/565f3431469c64a8178b92ea [status code] 405 [reason phrase] Method Not Allowed",
  "body": {
    "error":{ "code":405, "message":"" }
  }
} 
```

I believe this is due to breaking changes made to the endpoint in DoSomething/northstar#214.

### LINKED ISSUE #502: Authenticate admin users against their Northstar credentials
Right now, admin users have separate passwords for each instance of the Voting App, which is like super confusing. It'd be great to use [Northstar-PHP](https://github.com/DoSomething/northstar-php#laravel-authentication) to handle authentication. :lock_with_ink_pen:

### PR DESCRIPTION
**Pull request by katiecrane**
- use Northstar-PHP
### Issues:

Fixes #487 
Fixes #502

### CODE REVIEW

File: app/Services/Registrar.php [hunk 1]
```diff
@@ -85,7 +78,8 @@ public function create(array $data)
             }
 
             $user->country_code = get_country_code();
-            $user->northstar_id = $this->northstar->register($user);
+
+            $northstar_user = Northstar::createUser($user);
```
Comment (DFurnes) [inline app/Services/Registrar.php]: I think we need to do some transformations before making this request. For example, Voting App saves phone numbers as `phone` whereas Northstar expects them to be given as `mobile`. (Although maybe we should just rename that database column to be consistent with what we use elsewhere?)

We should also attach a `source = <voting_app_name>` to this request so we can track where new Northstar users come from.

File: app/Http/Controllers/VotesController.php [hunk 2]
```diff
@@ -80,7 +72,7 @@ public function store(VoteRequest $request)
             event(new UserCastFirstVote($vote));
         }
 
-        $this->northstar->storeInterest($user, $vote->candidate);
+        $northstar_user = Northstar::updateUser($user, $vote->candidate);
```
Comment (DFurnes) [inline app/Http/Controllers/VotesController.php]: Oh, this should be `$northstarUser`! :camel:

File: app/Services/Registrar.php (hunk 1 above)
Comment (DFurnes) [inline app/Services/Registrar.php]: - [x] `phone` to `mobile`
- [ ] adding `source` to the Northstar user

You can make a `$payload = $user->toArray()` to append the source to (and then submit to Northstar) so that you don't run into issues when running `$user->save()` down below.

**Comment by DFurnes** [comment]
Looks good! :shipit:
